### ISSUE TITLE
An edge case

### ISSUE THREAD

**Issue by markhc** [dude719/Windbg2Struct#1]
While writing my own version of this I came upon this interesting case that I thought you should know.

Run your script on this:

```
dt nt!_RTL_BALANCED_NODE
   +0x000 Children         : [2] Ptr64 _RTL_BALANCED_NODE
   +0x000 Left             : Ptr64 _RTL_BALANCED_NODE
   +0x008 Right            : Ptr64 _RTL_BALANCED_NODE
   +0x010 Red              : Pos 0, 1 Bit
   +0x010 Balance          : Pos 0, 2 Bits
   +0x010 ParentValue      : Uint8B
```

The right output would be something like this:

```
typedef struct _RTL_BALANCED_NODE
{
    union
    {
        struct _RTL_BALANCED_NODE* Children[2];
        struct
        {
            struct _RTL_BALANCED_NODE* Left;
            struct _RTL_BALANCED_NODE* Right;
        };
    };
    union
    {
        uint64_t    ParentValue;
        uint8_t     Red : 1;
        uint8_t     Balance : 2;
    };
} RTL_BALANCED_NODE, *PRTL_BALANCED_NODE;
```

Things to note: 

- There's the obvious first union which you can probably see that isnt trivial to generate.
- The second union is a union of 2 bitfields and a non bitfield value. Note that your script would generate it like this:

```
    union
    {
        uint64_t    ParentValue;
        struct {
            uint64_t    Red : 1;
            uint64_t    Balance : 2;
        };
    };
```

That is wrong. The correct way to display it is
```
    union
    {
        uint64_t    ParentValue;
        uint8_t     Red : 1;
        uint8_t     Balance : 2;
    };
```
You can see this because of the Pos value of each bitfield. Both of them are at "Pos 0", meaning they have the same offset (i.e they are inside the union itself, not a struct inside a union).

**Comment by ajkhoury** [comment]
I noticed a lot of structs similar to this one aren't correct. I don't really have time to perfect this right now, otherwise i'd fix it up.
